export const GET_ERRORS = "GET_ERRORS";
export const GET_PROJECTS = "GET_PROJECTS";
//export const ADD_PROJECT = "ADD_PROJECT";
export const DELETE_PROJECTS = "DELETE_PROJECTS";
export const UPDATE_PROJECTS = "UPDATE_PROJECTS";
